sudo: required
dist: trusty

language: cpp

notifications:
  email:
      - cwelsh2@uw.edu

compiler: gcc

branches:
  only:
    - master
    - develop

services: docker

before_install:
  - docker pull ciaranwelsh/ubuntu-base

script:
  - docker run ciaranwelsh/ubuntu-base /bin/sh -c "wget https://raw.githubusercontent.com/CiaranWelsh/libroadrunner-deps/master/roadrunner_deps_build.py; python roadrunner_deps_build.py \"/libroadrunner-deps-install-docker\""


