name: BuildLibRoadRunnerDependencies

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    name: Build on ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: manylinux2014-release
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Release
          - name: manylinux2014-debug
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Debug
    runs-on: ${{ matrix.platform.os_name }}
    container:
      image: ${{ matrix.platform.container_image || '' }}

    steps:
      - name: Add libroadrunner dependencies binaries for manylinux platforms to the workspace
        if : matrix.platform.os_type == 'manylinux'
        shell : bash
        run: |
          cd ${RUNNER_WORKSPACE}
          mkdir -p install-libroadrunner-deps
          cd install-libroadrunner-deps
          echo "Copying libroadrunner dependencies binaries for manylinux platforms to the workspace" >> abcg.txt
          mkdir -p ${{ github.workspace }}/manylinux2014-artifacts/${{ matrix.platform.build_type }}
          cp -r ${RUNNER_WORKSPACE}/install-libroadrunner-deps/* ${{ github.workspace }}/manylinux2014-artifacts/${{ matrix.platform.build_type }}
          echo "checking the directory ${{ github.workspace }}/manylinux2014-artifacts/${{ matrix.platform.build_type }}"
          ls -l ${{ github.workspace }}/manylinux2014-artifacts/${{ matrix.platform.build_type }}

  upload_manylinux_artifacts:
    name: Upload manylinux artifacts
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
    runs-on: ubuntu-latest
    needs: build_on_OSs

    steps:
      - name: check the directory
        run: |
          echo "checking ${{ github.workspace }}"
          cd ${{ github.workspace }}
          pwd
          echo "checking ${{ github.workspace }}/manylinux2014-artifacts"
          ls
          echo "pwd"
          pwd
        

      - name: Upload libroadrunner dependencies binaries for manylinux platforms
        uses: actions/upload-artifact@v4
        with:
          name: libroadrunner-deps-manylinux2014-${{ matrix.build_type }}
          path: ${{ github.workspace }}/manylinux2014-artifacts/${{ matrix.build_type }}
