name: BuildLibRoadRunnerDependencies

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    name: Build on ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: manylinux2014-release
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Release
          - name: manylinux2014-debug
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Debug
    runs-on: ${{ matrix.platform.os_name }}
    container:
      image: ${{ matrix.platform.container_image || '' }}

    steps:
      - name: create a text file
        run: |
          cd ${{ github.workspace }}
          mkdir -p mydirectory
          cd mydirectory
          echo "Hello, world!" > mytextfile.txt

      - name: Upload libroadrunner dependencies binaries for manylinux platforms
        uses: actions/upload-artifact@v1
        with:
          name: libroadrunner-dependencies-manylinux
          path: ${{ github.workspace }}/mydirectory
