name: BuildLibRoadRunnerDependencies

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    name: Build on ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: manylinux2014-release
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Release
    runs-on: ${{ matrix.platform.os_name }}
    container:
      image: ${{ matrix.platform.container_image || '' }}

    steps:
      - name: Checkout libroadrunner dependencies
        uses: actions/checkout@v3

      - name: Create a text file
        run: echo "Hello, world!" > hello.txt

      - name: list files in the host
        run: |
          pwd
          cd
          pwd