name: BuildLibRoadRunnerDependencies

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    name: Build on ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: manylinux2014-release
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Release
    runs-on: ${{ matrix.platform.os_name }}
    container:
      image: ${{ matrix.platform.container_image || '' }}

    steps:
      - name: Checkout libroadrunner dependencies
        uses: actions/checkout@v3

      - name: build glibc from source
        run: |
          cd ${RUNNER_WORKSPACE}
          mkdir glibc
          curl -L https://ftp.gnu.org/gnu/libc/glibc-2.31.tar.gz
          tar -xvf glibc-2.31.tar.gz
          rm glibc-2.31.tar.gz
          cd glibc-2.31
          mkdir build-glibc
          mkdir install-glibc
          cd build-glibc
          ../configure --prefix=${RUNNER_WORKSPACE}/glibc/install-glibc
          make -j4
          sudo make install
          export LD_LIBRARY_PATH=${RUNNER_WORKSPACE}/glibc/install-glibc/lib:$LD_LIBRARY_PATH
          export "PATH=${RUNNER_WORKSPACE}/glibc/install-glibc/bin:$PATH" >> $GITHUB_PATH

      - name: Upload libroadrunner dependencies binaries
        uses: actions/upload-artifact@v4
        with:
          name: libroadrunner-deps-${{ matrix.platform.name }}-${{ matrix.platform.build_type }}
          path: /tmp