name: BuildLibRoadRunnerDependencies

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    name: Build on ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: manylinux2014-release
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Release
          - name: ubuntu-latest-to-upload-manylinux2014-release
            os_type: ubuntu-to-upload
            os_name: ubuntu-latest
            build_type: Release
    runs-on: ${{ matrix.platform.os_name }}
    container:
      image: ${{ matrix.platform.container_image || '' }}

    steps:
      - name: Checkout libroadrunner dependencies
        uses: actions/checkout@v3

      - name: Generate data
        run: echo "Hello, world!" > generated_data.txt

      # Set up workspace to share data
      - name: Set up workspace
        run: mkdir -p ${{ github.workspace }}/shared && cp generated_data.txt ${{ github.workspace }}/shared

      - name: Retrieve data
        run: |
          cp ${{ github.workspace }}/shared/generated_data.txt .
          ls -l